### PR TITLE
git: make code owners apply to all files

### PR DESCRIPTION
**Pull request by JoepVanlier**
**Why this PR?**
Because docs also need review :)

### CODE REVIEW

**Review by agom — APPROVED** [review]
:scroll:

**Review by dean0x7d — APPROVED** [review]

**Review by mwilkowski — APPROVED** [review]

**Review by mcsmurf — APPROVED** [review]
This is great work! It will make our code more robust and our product top notch.

**Review by jeromlangeveld — APPROVED** [review]

**Review by bkarpati — APPROVED** [review]
:corn:

**Review by lpingas — APPROVED** [review]
👍

**Review by tiagobonetti — APPROVED** [review]
`honk` with the gaggle

**Pull request merged**
